# Generated by Django 3.1.7 on 2021-02-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechShelterApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joindate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
