# Generated by Django 3.1.7 on 2021-02-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechShelterApp', '0004_auto_20210225_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
    ]
