# Generated by Django 3.1.7 on 2021-03-11 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechShelterApp', '0006_deliverylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='seller',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
