# Generated by Django 3.1.7 on 2021-03-19 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechShelterApp', '0007_auto_20210311_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedtech',
            name='tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TechShelterApp.tech'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
