# Generated by Django 3.1.7 on 2021-03-19 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TechShelterApp', '0008_auto_20210320_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylocation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
